# https://projecteuler.net/archives

# =============================================================================
# Problem 1, Multiples of 3 and 5
# =============================================================================

# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

# Find the sum of all the multiples of 3 or 5 below 1000.

# def multiples_3_5
#   sum = 0
#   for i in 0...1000
#     sum += i if i % 3.to_f == 0 || i % 5.to_f == 0
#   end
#   sum
# end

# puts multiples_3_5

# =============================================================================
# Problem 2, Even Fibonacci numbers
# =============================================================================

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# def even_fibonacci_numbers
#   arr = [1]
#   sum = 0
#   previous = 1
#   on = 1
#   while on < 4000000
#     if on == 1
#       on += previous
#       sum += on
#     else
#       aux = on
#       on += previous
#       previous = aux
#       sum += on if on % 2 == 0
#     end
#   end
#   sum
# end

# puts even_fibonacci_numbers
# =============================================================================
# Problem 3, Largest prime factor
# =============================================================================

# The prime factors of 13195 are 5, 7, 13 and 29.
# What is the largest prime factor of the number 600851475143 ?